Update the BSP script
Allow it to be called independently also improve its overall structure.

Signed-off-by: Xing Lei <xing.lei@nxp.com>

diff --git a/tools/create_composite_firmware b/tools/create_composite_firmware
--- a/tools/create_composite_firmware
+++ b/tools/create_composite_firmware
@@ -1,13 +1,11 @@
 #!/bin/bash
 #
-# Copyright 2017-2021 NXP
+# Copyright 2017-2021,2026 NXP
 #
 # SPDX-License-Identifier: BSD-3-Clause
 #
 # A generic function to create NOR/QSPI/XSPI/NAND flash or SD/eMMC card composite firmware
 # which consists of customizable images separately.
-#
-# ${BOOTLOADER_TYPE} can be uboot, uefi
 #
 # ${BOOT_TYPE} can be sd, emmc, qspi, xspi, nor, nand, defined in configs/board/<machine>.conf
 #
@@ -19,11 +17,55 @@
 # - configs/board/common/layerscape_memorylayout.cfg
 # - configs/board/<machine>.conf
 #
-# Usage: bld fw -m <machine>  [ -b <boottype> ]
+# Can be called independently from the Makefile
 #
 
+log_mute() {
+  case "${LOG_LEVEL:-2}" in
+    0)
+      "$@"
+      ;;
+    1)
+      "$@" >/dev/null
+      ;;
+    2)
+      "$@" >/dev/null 2>&1 || {
+        echo "Error: Command '$*' failed. Please export LOG_LEVEL=0 and retry."
+        exit 1
+      }
+      ;;
+	*)
+		echo "Error LOG_LEVEL must be 0, 1 or 2" >&2
+		exit 1
+		;;
+  esac
+}
+
+
+fbprint_n() {
+    echo -e "${green}\n$1 ${NC}"
+}
+
+fbprint_d() {
+    echo -e "${GREEN}$1     [Done] ${NC}"
+}
+
+GREEN='\e[1;32m'
+green='\e[0;32m'
+NC='\e[0m'
+
 create_composite_firmware() {
-    if [ -z "${BOOTTYPE}" -o "${BOOTTYPE}" = all ] && [ -n "$BOOT_TYPE" ]; then
+    set -e -o pipefail
+    if [ $SOCFAMILY = LS ]; then
+        . $FBDIR/configs/board/common/layerscape_memorylayout.cfg
+    elif [ $SOCFAMILY = IMX ]; then
+        . $FBDIR/configs/board/common/imx_memorylayout.cfg
+    fi
+
+    local conf_file="$FBDIR/configs/board/${MACHINE}.conf"
+    . "$conf_file"
+
+    if [ -z "${BOOTTYPE}" ] && [ -n "$BOOT_TYPE" ]; then
         BOOTTYPELIST=${BOOT_TYPE}
     elif [ -n "${BOOTTYPE}" ]; then
         BOOTTYPELIST=${BOOTTYPE}
@@ -31,59 +73,83 @@ create_composite_firmware() {
         BOOTTYPELIST=sd
     fi
 
-
     [ -z "${DISK_BOOTLOADER_OFFSET}" ] && DISK_BOOTLOADER_OFFSET=4096
 
     for boottype in ${BOOTTYPELIST}; do
+        secopt=""
+        [ "${CONFIG_SECURE_BOOT}" = "y" ] && secopt="_sec"
 
-        if [ "${SECURE_TYPE}" = "secure" ]; then
-            secopt=_sec && secstr=_secure
-        else
-            secopt="" && secstr=""
-        fi
-
-        blname="${boottype}boot${secstr}"
+        blname="${boottype}boot${secopt}"
         fw_img=$FBOUTDIR/images/firmware_${MACHINE}_${blname}.img
         rm -f ${fw_img} && img_offset="" && img_file=""
 
-        for i in $(seq 1 ${MAX_COMPOSITE_IMG_NUM}); do
+        for i in $(seq 1 "${MAX_COMPOSITE_IMG_NUM}"); do
             img_offset=$(eval echo '$'COMPOSITE_IMG"$i"_OFFSET)
+            img_file=""
 
-            if [ "${MULTI_BOOTTYPE}" = "true" ]; then
-                [ "${SECURE_TYPE}" != "secure" -a $i = $SECURE_HEADER_NUM ] && continue
-                if [ $i = 1 -o $i = $SECURE_HEADER_NUM ]; then
-                    img_file=$(eval echo '$'COMPOSITE_IMG"$i"_FILE_"$boottype""$secopt")
+            if [ "${SOCFAMILY}" = "LS" ]; then
+                # Skip secure header if secure boot is disabled
+                [ "${CONFIG_SECURE_BOOT}" != "y" ] && [ "$i" = "${SECURE_HEADER_NUM}" ] && continue
+
+                # Build search candidates by priority
+                candidates=""
+                if [ "${CONFIG_SECURE_BOOT}" = "y" ]; then
+                    case $i in
+                        1|2|4|5|6)
+                        # Priority 1: _<boottype>_sec, Priority 2: _sec
+                        candidates="COMPOSITE_IMG${i}_FILE_${boottype}_sec COMPOSITE_IMG${i}_FILE_sec"
+                        ;;
+                        *)
+                        # Standard secure priority
+                        candidates="COMPOSITE_IMG${i}_FILE"
+                        ;;
+                    esac
                 else
-                    img_file=$(eval echo '$'COMPOSITE_IMG"$i"_FILE"$secopt")
+                    # Non-secure mode specific filenames
+                    candidates="COMPOSITE_IMG${i}_FILE_${boottype} COMPOSITE_IMG${i}_FILE"
                 fi
 
-                [ $i = 1 -a -z "${img_file}" ] && rm -f ${fw_img} && break
+                # Find the first defined variable in candidates
+                for var in $candidates; do
+                    img_file=$(eval echo '$'"$var")
+                    [ -n "$img_file" ] && break
+                done
 
-                if [ -z "${img_file}" -a "${SECURE_TYPE}" = "secure" ] && [ $i = 1 -o $i = 2 -o $i = 5 ]; then
-                    img_file=$(eval echo '$'COMPOSITE_IMG"$i"_FILE_sec)
-                fi
-                [ -z "${img_file}" ] && img_file=$(eval echo '$'COMPOSITE_IMG"$i"_FILE)
-                [ -z "${img_file}" -a $i = 2 ] && img_file=$(eval echo '$'COMPOSITE_IMG"$i"_FILE_"$boottype""$secopt")
+
+                # Critical check: if the first image (usually bootloader) is missing, abort this firmware
+                [ "$i" = 1 ] && [ -z "${img_file}" ] && rm -f "${fw_img}" && break
             else
+                # Default logic for non-LS families
                 img_file=$(eval echo '$'COMPOSITE_IMG"$i"_FILE_"$boottype")
             fi
 
-            [ $i = $MAX_COMPOSITE_IMG_NUM -a "$COMPOSITE_FW_NO_ITB_TYPE" = "$boottype" ] && break
+            # Skip ITB image if specified by type
+            [ "$i" = "${MAX_COMPOSITE_IMG_NUM}" ] && [ "$COMPOSITE_FW_NO_ITB_TYPE" = "$boottype" ] && break
 
-            if [ -n "${img_file}" ]; then
-                if [ -e "$FBOUTDIR/${img_file}" ]; then
-                    log_mute echo " Writing ${img_offset} <---> ${FBOUTDIR##*/}/${img_file}"
-                    if [ $i != 1 ] && [ "${boottype}" = "sd" -o "${boottype}" = "emmc" ]; then
-                        img_offset=`printf "%d - %d\n" ${img_offset} ${DISK_BOOTLOADER_OFFSET} | bc`
-                    fi
-                    offset=`printf "%d / 1024\n" ${img_offset} | bc`
-                    dd if=$FBOUTDIR/${img_file} of=${fw_img} bs=1K seek=${offset} 2>/dev/null
+            # Write image to firmware if file exists
+            if [ -n "${img_file}" ] && [ -e "$FBOUTDIR/${img_file}" ]; then
+                log_mute echo " Writing ${img_offset} <---> ${FBOUTDIR##*/}/${img_file}"
+
+                target_offset=${img_offset}
+                # Adjust offset for SD/eMMC boot media (skipping MBR/partition table area)
+                if [ "$i" != 1 ] && { [ "${boottype}" = "sd" ] || [ "${boottype}" = "emmc" ]; }; then
+                    target_offset=$((img_offset - DISK_BOOTLOADER_OFFSET))
                 fi
+
+                # Convert byte offset to 1K blocks for dd
+                seek_val=$((target_offset / 1024))
+                dd if="$FBOUTDIR/${img_file}" of="${fw_img}" bs=1K seek=${seek_val} conv=notrunc 2>/dev/null
             fi
         done
-        [ -f ${fw_img} ] && fbprint_d "${fw_img}"; echo
+        [ -f "${fw_img}" ] && fbprint_d "${fw_img}"; echo
     done
-	if [ -f $PKGDIR/apps/security/cst/srk_hash.txt -a $SOCFAMILY = LS ]; then
-		cp -f $PKGDIR/apps/security/cst/srk* $FBOUTDIR/images/
-	fi
+
+    # Copy SRK hash files for LS family if security tools exist
+    if [ -f "$PKGDIR/apps/security/cst/srk_hash.txt" ] && [ "$SOCFAMILY" = "LS" ]; then
+        cp -f "$PKGDIR/apps/security/cst/srk"* "$FBOUTDIR/images/"
+    fi
 }
+
+if [ "${BASH_SOURCE[0]}" = "$0" ]; then
+    create_composite_firmware "$@"
+fi
