add verifying the machine and fix a gst_python script issue
Signed-off-by: Andy Tang <andy.tang@nxp.com>

diff --git a/tools/flex-builder b/tools/flex-builder
--- a/tools/flex-builder
+++ b/tools/flex-builder
@@ -35,7 +35,7 @@ Most used example with separate command:
  bld clean-bsp                   # clean obsolete BSP (u-boot/atf/firmware) images
  bld clean-linux                 # clean obsolete linux image
  bld clean-apps -m <machine>     # clean the obsolete <machine>-specific apps components binary images
- bld clean                       # equal to "bld clean bsp" + "bld clean linux" + "bld clean-apps -m <machine>"
+ bld clean -m <machine>          # equal to "bld clean bsp" + "bld clean linux" + "bld clean-apps -m <machine>"
  bld clean-rfs -m <machine>      # clean target debian-based rootfs for <machine>
 
  bld docker                      # create or attach docker container to build in docker
@@ -410,12 +410,11 @@ check_board_valid() {
 		echo -e "Error: Please specify the board, for example: bld -m imx8mpevk \n"
 		exit 1
 	fi
-	if ! echo "$LS_MACHINE_LIST" | grep -qw "$MACHINE" && ! echo "$IMX_MACHINE_LIST" | grep -qw "$MACHINE"; then
-		echo "Error: Invalid board: '$MACHINE'."
-		echo "LS_MACHINE_LIST: $LS_MACHINE_LIST"
-		echo "IMX_MACHINE_LIST: $IMX_MACHINE_LIST"
-		exit 1
-	fi
+    [[ " $ls_machine_list " =~ " $1 " ]] || [[ " $imx_machine_list " =~ " $1 " ]] && exit 0
+    echo "Error: Invalid board: '$MACHINE'."
+    echo "LS_MACHINE_LIST: $LS_MACHINE_LIST"
+    echo "IMX_MACHINE_LIST: $IMX_MACHINE_LIST"
+    exit 1
 }
 
 check_binfmt_qemu() {
